---
fixtures:
  repositories:
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    yumrepo_core: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
  symlinks:
    rsyslog: "#{source_dir}"
